### ISSUE TITLE
Prosze nie dodawac glupich issues

### ISSUE THREAD

**Issue by Creper132** [Creper132/shutdown-utility-batch#1]
Dowidzenia

**Comment by lisqu16** [comment]
ale o co ci chodzi, te issue są równo z twoim poziomem intelektualnym

**Comment by pankoza-pl** [comment]
lisqu to dzieciak od enderk

**Comment by lisqu16** [comment]
nie żeby coś ale jestem od ciebie starszy, więc nazywając mnie dzieckiem, uważasz również siebie za "dziecko"

**Comment by lisqu16** [comment]
zresztą twoją mentalność bardzo dobrze przedstawia twój avatar @pankoza-pl

**Comment by Creper132** [comment]
ludzie możecie sie ogarnąc, lisqu jest od programistazpolski!

**Comment by chickeeen** [comment]
dokładnie!!! to jest skandal!!!!!!! lisqu pewnie już wytacza pozew o zniesławienie przez panakoze-pl!!!!!!!!

**Comment by Creper132** [comment]
mozesz programistazpolsk ogarnqc

**Comment by ProgramistaZpolski** [comment]
> mozesz programistazpolsk ogarnqc

co ja ci niby robię

**Comment by chickeeen** [comment]
@programistazpolski ogarnqam cię
